-- Migration 001 : table d'exemple
-- À exécuter dans le SQL Editor de Supabase (ou via la CLI : supabase db push).
-- Convention : chaque table a RLS activé + 4 policies (select/insert/update/delete) to authenticated.

create table if not exists public.ma_table (
  id bigint generated by default as identity primary key,
  label text not null,
  created_at timestamptz default now()
);

alter table public.ma_table enable row level security;

create policy "sel" on public.ma_table for select to authenticated using (true);
create policy "ins" on public.ma_table for insert to authenticated with check (true);
create policy "upd" on public.ma_table for update to authenticated using (true);
create policy "del" on public.ma_table for delete to authenticated using (true);
